config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :neighborhoods

      resources :bookmarks

      resources :dishes

      resources :cuisines

      resources :venues

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "venues#index"
  resources :neighborhoods
  resources :bookmarks
  resources :dishes
  resources :cuisines
  resources :venues
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
class Dish < ApplicationRecord
  # Direct associations

  has_many   :bookmarks,
             dependent: :destroy

  belongs_to :cuisine,
             counter_cache: true

  # Indirect associations

  has_many   :specialists,
             through: :bookmarks,
             source: :venue

  has_many   :fans,
             through: :bookmarks,
             source: :user

  # Validations

  validates :name, uniqueness: true

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/dishes_controller.rb
class Api::V1::DishesController < Api::V1::GraphitiController
  def index
    dishes = DishResource.all(params)
    respond_with(dishes)
  end

  def show
    dish = DishResource.find(params)
    respond_with(dish)
  end

  def create
    dish = DishResource.build(params)

    if dish.save
      render jsonapi: dish, status: :created
    else
      render jsonapi_errors: dish
    end
  end

  def update
    dish = DishResource.find(params)

    if dish.update_attributes
      render jsonapi: dish
    else
      render jsonapi_errors: dish
    end
  end

  def destroy
    dish = DishResource.find(params)

    if dish.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: dish
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[show edit update destroy]

  def index
    @q = Dish.ransack(params[:q])
    @dishes = @q.result(distinct: true).includes(:cuisine, :bookmarks,
                                                 :fans, :specialists).page(params[:page]).per(10)
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @dish = Dish.new
  end

  def edit; end

  def create
    @dish = Dish.new(dish_params)

    if @dish.save
      message = "Dish was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @dish, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @dish.update(dish_params)
      redirect_to @dish, notice: "Dish was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @dish.destroy
    message = "Dish was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to dishes_url, notice: message
    end
  end

  private

  def set_dish
    @dish = Dish.find(params[:id])
  end

  def dish_params
    params.require(:dish).permit(:name, :cuisine_id)
  end
end

app/views/dishes/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Dish #<%= dish.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= dish.name %></dd>

      <dt>Cuisine</dt>
      <dd>
        <% if @dish.cuisine.present? %>
          <%= link_to dish.cuisine, dish.cuisine %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back dish, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_dish_url(dish), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to dish, method: :delete, data: { confirm: "Do you really want to delete this dish?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(dish.updated_at) %> ago
  </div>
</div>

app/views/dishes/_dish_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#dish_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @dish.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <% if current_user == bookmark.user %>
          <%= link_to bookmark, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="dish_bookmarks_new_form">
        <%= render partial: "dishes/dish_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/dishes/_dish_bookmarks_new_form.html.erb
<%= form_with(model: @bookmark, local: true) do |f| %>

  <%= f.hidden_field :dish_id, value: @dish.id %>

  <div class="form-group">
    <%= f.label :venue_id %>

    <%= f.collection_select :venue_id, Venue.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>

    <%= f.file_field :image, class: "form-control" %>
  </div>

  <%= f.submit "Create bookmark", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/dishes/_dish_fans.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Fans
  </div>

  <ul class="list-group list-group-flush">
    <% @dish.fans.each do |user| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/users/<%= user.id %>">
          <%= user %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/dishes/_dish_specialists.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Specialists
  </div>

  <ul class="list-group list-group-flush">
    <% @dish.specialists.each do |venue| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/venues/<%= venue.id %>">
          <%= venue %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/dishes/_dishes_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "dishes_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :cuisine_name_cont, "Cuisine name contains" %>
    <%= f.text_field :cuisine_name_cont, :class => "form-control", :placeholder => "Cuisine name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :bookmarks_notes_cont, "Bookmarks notes contains" %>
    <%= f.text_field :bookmarks_notes_cont, :class => "form-control", :placeholder => "Bookmarks notes contains" %>
  </div>

  <div class="form-group">
    <%= f.label :fans_username_cont, "Fans username contains" %>
    <%= f.text_field :fans_username_cont, :class => "form-control", :placeholder => "Fans username contains" %>
  </div>

  <div class="form-group">
    <%= f.label :specialists_name_cont, "Specialists name contains" %>
    <%= f.text_field :specialists_name_cont, :class => "form-control", :placeholder => "Specialists name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/dishes" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#dishes_filters">
  Show filters
</a>

app/views/dishes/_form.html.erb
<% was_validated = dish.errors.any? %>

<%= form_with(model: dish, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = dish.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% dish.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% cuisine_class = "form-control" %>
    <% cuisine_was_invalid = dish.errors.include?(:cuisine) %>

    <% if was_validated %>
      <% if cuisine_was_invalid %>
        <% cuisine_class << " is-invalid" %>
      <% else %>
        <% cuisine_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :cuisine_id %>
    <%= f.collection_select :cuisine_id, Cuisine.all, :id, :to_s, {}, class: "form-control" %>
    <% if cuisine_was_invalid %>
      <% dish.errors.full_messages_for(:cuisine).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/dishes/_list_item.html.erb
<%= link_to dish, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= dish %>
    <small class="text-muted">
      <%= time_ago_in_words(dish.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/dishes/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Dish #<%= @dish.id %>
      </h2>

      <div class="card-body">
        <%= render "form", dish: @dish %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dishes/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Dishes

      <%= link_to new_dish_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "dishes/dishes_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Dishes

        <%= link_to new_dish_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @dishes, partial: "list_item", as: :dish %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @dishes, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/dishes/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Dish
      </h2>

      <div class="card-body">
        <%= render "form", dish: @dish %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @dish, partial: "card", as: :dish %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dishes/dish_bookmarks" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dishes/dish_fans" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dishes/dish_specialists" %>
  </div>
</div>