config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :neighborhoods

      resources :bookmarks

      resources :dishes

      resources :cuisines

      resources :venues

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "venues#index"
  resources :neighborhoods
  resources :bookmarks
  resources :dishes
  resources :cuisines
  resources :venues
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  # Direct associations

  has_many   :venues,
             dependent: :nullify

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/neighborhoods_controller.rb
class Api::V1::NeighborhoodsController < Api::V1::GraphitiController
  def index
    neighborhoods = NeighborhoodResource.all(params)
    respond_with(neighborhoods)
  end

  def show
    neighborhood = NeighborhoodResource.find(params)
    respond_with(neighborhood)
  end

  def create
    neighborhood = NeighborhoodResource.build(params)

    if neighborhood.save
      render jsonapi: neighborhood, status: :created
    else
      render jsonapi_errors: neighborhood
    end
  end

  def update
    neighborhood = NeighborhoodResource.find(params)

    if neighborhood.update_attributes
      render jsonapi: neighborhood
    else
      render jsonapi_errors: neighborhood
    end
  end

  def destroy
    neighborhood = NeighborhoodResource.find(params)

    if neighborhood.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: neighborhood
    end
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: %i[show edit update destroy]

  def index
    @q = Neighborhood.ransack(params[:q])
    @neighborhoods = @q.result(distinct: true).includes(:venues).page(params[:page]).per(10)
  end

  def show
    @venue = Venue.new
  end

  def new
    @neighborhood = Neighborhood.new
  end

  def edit; end

  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    if @neighborhood.save
      redirect_to @neighborhood,
                  notice: "Neighborhood was successfully created."
    else
      render :new
    end
  end

  def update
    if @neighborhood.update(neighborhood_params)
      redirect_to @neighborhood,
                  notice: "Neighborhood was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @neighborhood.destroy
    redirect_to neighborhoods_url,
                notice: "Neighborhood was successfully destroyed."
  end

  private

  def set_neighborhood
    @neighborhood = Neighborhood.find(params[:id])
  end

  def neighborhood_params
    params.require(:neighborhood).permit(:name)
  end
end

app/views/neighborhoods/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Neighborhood #<%= neighborhood.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= neighborhood.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back neighborhood, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_neighborhood_url(neighborhood), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to neighborhood, method: :delete, data: { confirm: "Do you really want to delete this neighborhood?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(neighborhood.updated_at) %> ago
  </div>
</div>

app/views/neighborhoods/_form.html.erb
<% was_validated = neighborhood.errors.any? %>

<%= form_with(model: neighborhood, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = neighborhood.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% neighborhood.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/neighborhoods/_list_item.html.erb
<%= link_to neighborhood, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= neighborhood %>
    <small class="text-muted">
      <%= time_ago_in_words(neighborhood.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/neighborhoods/_neighborhood_venues.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Venues

    <a data-toggle="collapse" href="#neighborhood_venues_new_form">
      Add venue
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @neighborhood.venues.each do |venue| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to venue, venue %>

        <%= link_to venue, method: :delete, data: { confirm: "Do you really want to delete this venue" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="neighborhood_venues_new_form">
        <%= render partial: "neighborhoods/neighborhood_venues_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/neighborhoods/_neighborhood_venues_new_form.html.erb
<%= form_with(model: @venue, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>

    <%= f.text_field :address, class: "form-control" %>
  </div>

  <%= f.hidden_field :neighborhood_id, value: @neighborhood.id %>

  <%= f.submit "Create venue", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/neighborhoods/_neighborhoods_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "neighborhoods_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :venues_name_cont, "Venues name contains" %>
    <%= f.text_field :venues_name_cont, :class => "form-control", :placeholder => "Venues name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/neighborhoods" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#neighborhoods_filters">
  Show filters
</a>

app/views/neighborhoods/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Neighborhood #<%= @neighborhood.id %>
      </h2>

      <div class="card-body">
        <%= render "form", neighborhood: @neighborhood %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/neighborhoods/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Neighborhoods

      <%= link_to new_neighborhood_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "neighborhoods/neighborhoods_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Neighborhoods

        <%= link_to new_neighborhood_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @neighborhoods, partial: "list_item", as: :neighborhood %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @neighborhoods, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/neighborhoods/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Neighborhood
      </h2>

      <div class="card-body">
        <%= render "form", neighborhood: @neighborhood %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/neighborhoods/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @neighborhood, partial: "card", as: :neighborhood %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "neighborhoods/neighborhood_venues" %>
  </div>
</div>